# wtf, where's the yml template?!
# This is embarrasing! Asking AI & using AI suggester again to help me write again!?
# Had no shame!! Why only in Markdown?!
# (JOELwindows7)

name: Levels & Mods Submit
description: Submit levels & mods without using Fork & Pull Request
title: "[Level]: "
labels: ["level", "triage"]
#projects: ["octo-org/1", "octo-org/44"]
assignees:
  - JOELwindows7
body:
  - type: markdown
    id: info
    attributes:
      value: |
        # You chose to Submit Levels without using Git way!
        Hello? Yuhuu..!!, You are submitting a level without Git?  
        C'mon! It's easy! Now that you have GitHub Account, all you have to do, is to go back to this Source code page again. 
        - Press `Fork` top right. 
        - Now, just insert your level into folder `maps` (`Add New Files` there & drag & drop). For other files, see [PK3](https://zdoom.org/wiki/Using_ZIPs_as_WAD_replacement) structures on ZDoom Wiki
        - commit, push (upload) to your fork
        - Pull Request et voila!

        The Full Instruction is [right here!](/CONTRIBUTING.md)

        ## Required Files:

        You must provide the following files:
        - `the_level.wad` / `the_level.pk3` / `the_level.pk7` / `the_level.7z` / `the_level.zip`

        ## Info:
  - type: input
    id: level_name
    attributes:
      label: Level / Mod Name
      description: Level `Title` that will be written to main `MAPINFO.txt`
      placeholder: ex. MyCoolLevel.wad / My Cool Level
    validations:
      required: true
  - type: input
    id: download_url
    attributes:
      label: Download URL
      description: Where did you upload the level so we can retrive it?
      placeholder: https://cloud.example.com/share/eA7Tb7
    validations:
      required: true
  - type: markdown
    id: tips_desc
    attributes:
      value: |
        > [!TIP]
        > You can attempt to attach wad files directly here!, since level only WAD files are typically very small.  
        > Always make sure to notify us manually once you've submitted this issue, just in case.
  - type: textarea
    id: describe
    attributes:
      label: Description
      description: Describe your level contents
      placeholder: This is my cool level, it got bla bla bla, and this this this..
    validations:
      required: true