# wtf, where's the yml template?!
# This is embarrasing! Asking AI again to help me write again!?
# Had no shame!! Why only in Markdown?!
# (JOELwindows7)

name: Level Submit
description: Submit a level!
title: "[Level]: "
labels: ["level", "triage"]
#projects: ["octo-org/1", "octo-org/44"]
assignees:
  - JOELwindows7
body:
  - type: markdown
    attributes:
      value: |
        # You chose to Submit Levels without using Git way!
        Hello? Yuhuu..!!, You are submitting a level without Git?  
        C'mon! It's easy! Now that you have GitHub Account, all you have to do, is to go back to this Source code page again. 
        Press `Fork` top right. Now, just insert your level into folder `maps` (`Add New Files` there & drag & drop), commit, push (upload) to your fork, Pull Request et voila!

        The Full Instruction is [right here!](/CONTRIBUTING.md)

        ## Required File:

        You must provide the following files:
        - `the_level.wad`
  - type: input
    id: level_name
    label: Level Name
    required: true
  - type: input
    id: download_url
    label: Download URL
    required: true
  - type: textarea
    id: describe
    label: Description
    required: true